---
title: "Analisis Descriptivo"
author: "Abraham Zamudio"
date: "2023-02-19"
output: flexdashboard::flex_dashboard
---

Visualizaciones {data-icon="fa-signal"}
=================================================

### Grafico 1
```{r Erick}
library(ggplot2)
ggplot(mtcars, aes(mpg, qsec))+
  geom_point(aes(size = hp) , alpha = 0.4)+
  facet_grid(factor(cyl) ~ factor(am), scale = "free")+
    xlab("Variable Independiente")+
    ylab("Var. Dependiente")+
    ggtitle("Dataset : mtcasrs")+
    labs(size = "Caballos de Fuerza")
```

### Grafico 2 
```{r Flor}
library(gridExtra)
df <- data.frame(x = 1:10, y = rnorm(100))
p1 <- ggplot(df, aes(x,y)) + geom_point()
p2 <- ggplot(df, aes(y)) + geom_histogram()
grid.arrange(p1, p2)
```

Tablas {data-icon="fa-table"}
=================================================
### Tabla 1
```{r}
knitr::kable(head(mtcars[, 1:4]), "simple")
```

### Tabla 2
```{r}
m <- lm(dist ~ speed, data = cars)
d <- coef(summary(m))
knitr::kable(d)
```


<!-- Esto es lo que hemos modificado : la tercera pestaña  -->
Graficos usando  plotly {data-icon="fa-table"}
=================================================

### Grafico pie

```{r}
library(plotly)

USPersonalExpenditure <- data.frame("Categorie"=rownames(USPersonalExpenditure), USPersonalExpenditure)
data <- USPersonalExpenditure[,c('Categorie', 'X1960')]

fig <- plot_ly(data, labels = ~Categorie, values = ~X1960, type = 'pie')
fig <- fig %>% layout(title = 'United States Personal Expenditures by Categories in 1960',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig

```

### Series de tiempo
```{r, include=FALSE}
library(tidyquant)
library(plotly)

getSymbols("GOOG",
             from = "2018-01-01",
             to = "2019-12-31")
```

```{r}
stock <- data.frame(GOOG$GOOG.Adjusted)
stock$GOOG.Adjusted <- stock$GOOG.Adjusted/stock$GOOG.Adjusted[1]
stock <- data.frame(stock,rownames(stock))
colnames(stock) <- append('GOOG','date')

fig <- plot_ly(stock, type = 'scatter', mode = 'lines')%>%
  add_trace(x = ~date, y = ~GOOG, name = 'GOOG')%>%
  layout(showlegend = F)
options(warn = -1)

fig <- fig %>%
  layout(
         xaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         yaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         plot_bgcolor='#e5ecf6', width = 900)

fig
```

